### ISSUE TITLE
SD009 - Unwanted exclusion of non-English initiatives

### ISSUE THREAD

**Issue by avanbremen** [Nictiz/api-requirements-docs#3]
See [SD009](https://nictiz.github.io/api-requirements-docs/v1.1.0/api-specification-and-documentation/#sd009-api-documentation-must-be-published-in-english).

## Issue description

Making the availability of English documentation mandatory (a MUST-have requirement) leads to the unwanted exclusion of non-English (for example, Dutch) initiatives.

## Motivation for change

It is of crucial importance for the success of the API strategy that we welcome as many APIs as possible on the “Open API” standardization level and stimulate improvement (conformance to SHOULD-have requirements) and growth to higher levels of standardization.

API specifications that include non-English (for example, Dutch) documentation should not be excluded from such an important initiative as the API strategy merely based on their language.

Availability of English documentation is important due to international aspirations with regards to data availability, but as a MUST-have the weight and implications of these requirements are disproportionate to other (for example, technical) requirements.

## Proposal for change

Make the availability of English documentation a SHOULD-have requirement, rather than a MUST-have requirement.

## Additional notes

When introducing a weighted scoring system, conformance to these (now SHOULD-have) requirements should be rewarded more heavily than other requirements. This will help motivate API specifiers to make API documentation available in English, in line with SD009’s original goal.

## Motivation of versioning

Changing requirements SD009, SD009.001 from MUST-have to SHOULD-have and making SD009.002, SD009.003 requirements conditional means that API specifications that complied with the previous MINOR version of the API Requirements for Dutch Healthcare (v1.1.0), still comply with the new version.

Therefore, when accepting this change (as a standalone change) the MINOR version number must be incremented (from v1.1.0 to **v1.2.0**) as described in [Versioning of this specification](https://nictiz.github.io/api-requirements-docs/v1.1.0/notational-conventions/#versioning-of-this-specification).

Because these requirements are now of a new form, their “Since version” should be changed from 1.0.0 to **1.2.0**.

**Comment by marc3112** [comment]
Although the main purpose of this requirement was to include non-dutch developers, I agree that this excludes too many initiatives. Therefore **I agree to this change**. Since an explanation is necessary for the Should, it will likely still be a matter of consideration.

**Comment by avanbremen** [comment]
Thanks for your feedback @marc3112. The proposed changes part of milestone [Release v1.2.0](https://github.com/Nictiz/api-requirements-docs/milestone/1) were submitted to the working group for review on July 4. Since there are no objections, the changes will now be accepted as part of the upcoming [API Requirements for Dutch Healthcare](https://nictiz.github.io/api-strategie-docs/) v1.2.0 release.

A big thank you to everyone who contributed.
