### ISSUE TITLE
DR-R002 - Unwanted exclusion of non-FHIR REST APIs

### ISSUE THREAD

**Issue by avanbremen** [Nictiz/api-requirements-docs#5]
See [DR-R002](https://nictiz.github.io/api-requirements-docs/v1.1.0/api-design-rules/#dr-r002-apis-must-use-singular-nouns-to-name-collection-resources).

## Issue description

Making usage of singular nouns mandatory (a MUST-have requirement) for naming REST API collection resources leads to the unwanted exclusion of many, especially non-FHIR, REST APIs.

## Motivation for change

DR-R002 states that “APIs MUST use singular nouns to name collection resources”. This, I believe, is based on the [FHIR Guide to Designing Resources](https://confluence.hl7.org/display/FHIR/Guide+to+Designing+Resources), which states that: *resource/element/operation names should be expressed as “singular”, particularly if the element is repeating*. In other words, use “Patient” rather than “Patients” for a collection of patients (patient information).

This requirement is in direct contradiction to [API Design Rule API-54]( https://gitdocumentatie.logius.nl/publicatie/api/adr/#api-54) from the [Dutch National API strategy]( https://docs.geostandaarden.nl/api/API-Strategie/) by Geonovum, which was considered when writing chapter [API design rules](https://nictiz.github.io/api-requirements-docs/v1.1.0/api-design-rules/#compliance-with-national-api-design-rules) of the API Requirements for Dutch Healthcare. Design Rule API-54 states: *Because a collection resource represents multiple things, the path segment describing the name of the collection resource must be written in the plural form*.

An argument for using plural form to name collection resources is that an empty collection or a collection that contains only one resource, is still a collection. Just as an empty array is still an array, an empty list is still a list, etc.

However, this approach would exclude FHIR REST APIs which is just as undesirable. As the FHIR Guide to Designing Resources provides Naming Rules & Guidelines for FHIR based APIs, the original goal of DR-R002 remains intact even with DR-R002 removed altogether.

Because we want to further the adoption of the API Requirements for Dutch Healthcare and welcome as many APIs as possible, including but not limited to FHIR and non-FHIR APIs, we must allow both plural and singular nouns for naming REST API collection resources.

## Proposal for change

Change DR-R002 so that APIs MUST consistently use either singular nouns **or** plural nouns to name collection resources.

## Additional notes

Original intent of DR-R002 will remain intact for FHIR based APIs due to standard FHIR Naming Rules & Guidelines.

## Motivation of versioning

Changing requirement DR-R002 so that using plural nouns to name collection resources is also allowed means that API specifications that complied with the previous MINOR version of the API Requirements for Dutch Healthcare (v1.1.0), still comply with the new version.

Therefore, when accepting this change (as a standalone change) the MINOR version number must be incremented (from v1.1.0 to **v1.2.0**) as described in [Versioning of this specification](https://nictiz.github.io/api-requirements-docs/v1.1.0/notational-conventions/#versioning-of-this-specification).

**Comment by marc3112** [comment]
The reason we diverted from the original API-rule from the Dutch National API strategy, is that this would exclude FHIR, which is not viable in dutch healthcare. Since this was an overcorrection, **I agree with this change**.

**Comment by avanbremen** [comment]
Thanks for your feedback @marc3112. The proposed changes part of milestone [Release v1.2.0](https://github.com/Nictiz/api-requirements-docs/milestone/1) were submitted to the working group for review on July 4. Since there are no objections, the changes will now be accepted as part of the upcoming [API Requirements for Dutch Healthcare](https://nictiz.github.io/api-strategie-docs/) v1.2.0 release.

A big thank you to everyone who contributed.
